name: CodeGuard Scan

on: 
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-codeguard-workflow:
    uses: Sanofi-Shared-GitHub-Apps/cyber-AST-Action_reusable/.github/workflows/code_guard_ast.yml@main
    with:
      production-branch: 'main'
      groups: 'crai-admins'
      cmdb: ""
      package-obsolescence: true
    secrets:
      DOCKER_AUTH_CONFIG: ${{ secrets.CODEGUARD_DOCKER_AUTH_CONFIG }}
      DOCKER_AUTH_ID: ${{ secrets.CODEGUARD_DOCKER_AUTH_ID }}
      CX_CLIENT_AUTH_ID: ${{ secrets.CX_CLIENT_AUTH_ID }}
      CX_CLIENT_AUTH_SECRET: ${{ secrets.CX_CLIENT_AUTH_SECRET }}
